#pragma once
#include <windows.h>
#include <atomic>
#include <string>

enum CtrlId {
    ID_MASTER_CHECK = 100, ID_STOP_BTN = 101, ID_BLEND_COMBO = 102,
    ID_HUE_CHECK = 200,  ID_HUE_SLIDER = 201,  ID_HUE_EDIT = 202,
    ID_CONTRAST_CHECK = 210, ID_CONTRAST_SLIDER = 211, ID_CONTRAST_EDIT = 212,
    ID_SAT_CHECK = 220, ID_SAT_SLIDER = 221, ID_SAT_EDIT = 222,
    ID_INVERT_CHECK = 230, ID_GRAY_CHECK = 240,
    ID_PIXELATE_CHECK = 250, ID_PIXELATE_SLIDER = 251, ID_PIXELATE_EDIT = 252,
    ID_GLITCH_CHECK = 260, ID_GLITCH_SLIDER = 261, ID_GLITCH_EDIT = 262,
    ID_EDGE_CHECK = 270,
    ID_CHROMA_CHECK = 300, ID_CHROMA_SLIDER = 301, ID_CHROMA_EDIT = 302, ID_CHROMA_MODE = 303, ID_CHROMA_SPEED = 304,
    ID_SHARP_CHECK = 310, ID_SHARP_SLIDER = 311, ID_SHARP_EDIT = 312,
    ID_WAVE_CHECK = 320, ID_WAVE_SLIDER = 321, ID_WAVE_EDIT = 322, ID_WAVE_SPEED = 323,
    ID_TRAIL_CHECK = 330, ID_TRAIL_FRAMES = 331, ID_TRAIL_OPACITY = 332,
};

struct SettingsWindowParams {
    HINSTANCE hInstance;
    std::atomic<bool>* overlayRunning;
};

int ShowSettingsWindow(SettingsWindowParams* params);
